import Head from 'next/head'
import Cards from '../components/Cards'
import Header from '../components/Header'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter()
  return (
    
    <div>
      <Head>
        <title>Take a Trip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
        <div className="pt-16 pl-24 pr-24 pb-16">        
          <h3 className="font-[Poppins] text-2xl pb-10 font-extrabold text-secondary">Best Places in Pakistan</h3>
          <div className="h-full flex sm:space-x-6 md:space-x-8 lg:space-x-10">
          <Cards imgUrl={'/lahore.jpg'} city="Lahore" distance="7km away"/>
          <Cards imgUrl={'/murree.png'} city="Murree" distance="7km away"/>
          <Cards imgUrl={'/isl.jpg'} city="Islamabad" distance="7km away"/>
          <Cards imgUrl={'/karachi.jpg'} city="Karachi" distance="10km away"/>
          </div>
        </div>
      <Footer />
    </div>
  )
}
